In [1]:
import numpy as np

In [54]:
#creat a 1D array of numbeers from 0 to 9 
import numpy as np
array = np.array([0,1,2,3,4,5,6,7,8,9])
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
#creat a 3x3 NumPy array of boolen vatues Trues 
import numpy as np
array = np.arange(0,1,3)
print ("multiply:",array * 3)

def array(c,d,e):
    return c * d == e

    

array(3,3,9)

multiply: [0]


True

In [8]:
#Extract all odd numbeers from array of 1-10
array = np.arange(1,10)
array
array[::2]




array([1, 3, 5, 7, 9])

In [11]:
#replace all odd numbers in array of 1-10 with the value -1
import numpy as np
array = np.arange(1,10)
array[::2] = -1
array

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

In [12]:
#Convert 1D array to a 2D array with 2 rows
array = np.arange(0,10). reshape(2,5)
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [119]:
#Creat 2 arrays and stack the 2 arrays vertically. calculate using np.dot  
A = np.arange (30,39). reshape (3,3)
B = np.arange (20,29). reshape (3,3)
C = np.dot (A,B)
print (C)

[[2145 2238 2331]
 [2352 2454 2556]
 [2559 2670 2781]]


In [120]:
#sum
Sum = np.sum(C)
print (Sum)

22086


In [148]:
#use numpy functions to write pattern without hardcoding 
import numpy as np

array = np.array([1,1,1,2,2,2,3,3,3,1,2,3,1,2,3])
newArray = array.reshape(5,3)

print (newArray)

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [1 2 3]
 [1 2 3]]


In [13]:
#remove repeating items from array B

A = np.array([1,2,3,4,5])
B = np.array([4,5,6,7,8,9])
print(A)
print(B[2:5])


[1 2 3 4 5]
[6 7 8]


In [17]:
#get items between 3 and 7 from a and b and sum together
Item1 = (A[3:])
Item2 = (B[3:7])
Item1, Item2


(array([4, 5]), array([7, 8, 9]))

In [164]:
Total = np.dot(Item1, Item2)
print (Total)

98


In [165]:
Sum = np.sum(Total)
print (Sum)

98
